# Sorting, Counting, Querying

We often have a large dataset but we are only interested in smaller sections of it.

Or we want to sort from largest to smallest.

Or perhaps we want to know how many instances of some value there is in the data.

Tonight we finally move beyond the basics to see the start of data analysis.

## Import libraries

In [1]:
## import libraries

import pandas as pd

## Upload Olympics datasets to this notebook.

### Import ```olympics-summer.csv``` and store in a dataframe called ```dfs``` (<a href="https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-summer.csv">link</a>).


### Import ```olympics-winter.csv``` and store in a dataframe called ```dfw``` (<a href="https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-winter.csv">link</a>).

In [2]:
## import summer data

dfs = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-summer.csv")
dfs

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
222547,135528,Marc Zwiebler,M,32.0,181.0,75.0,Germany,GER,2016,Rio de Janeiro,Badminton,Badminton Men's Singles,NaN
222548,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 100 metres,NaN
222549,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 200 metres,NaN
222550,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 4 x 100 metres Relay,NaN
222551,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN

In [3]:
dfs["Medal"].unique()

<StringArray>
[nan, 'Silver', 'Gold', 'Bronze']
Length: 4, dtype: str

In [4]:
## import winter data

dfw = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-winter.csv")
dfw

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN

## Get a sense of the data

In [5]:
## SUMMER
## what exactly do we have: columns, datatypes, etc.

dfs.info()

<class 'pandas.DataFrame'>
RangeIndex: 222552 entries, 0 to 222551
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            222552 non-null  int64
 1   Athlete Name  222552 non-null  str
 2   Sex           222552 non-null  str
 3   Age           213363 non-null  float64
 4   Height        170695 non-null  float64
 5   Weight        168698 non-null  float64
 6   Team          222552 non-null  str
 7   NOC           222552 non-null  str
 8   Year          222552 non-null  int64
 9   City          222552 non-null  str
 10  Sport         222552 non-null  str
 11  Event         222552 non-null  str
 12  Medal         34088 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 22.1 MB

In [6]:
## WINTER
## what exactly do we have: columns, datatypes, etc.

dfw.info()

<class 'pandas.DataFrame'>
RangeIndex: 48564 entries, 0 to 48563
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            48564 non-null  int64
 1   Athlete Name  48564 non-null  str
 2   Sex           48564 non-null  str
 3   Age           48279 non-null  float64
 4   Height        40250 non-null  float64
 5   Weight        39543 non-null  float64
 6   Team          48564 non-null  str
 7   NOC           48564 non-null  str
 8   Year          48564 non-null  int64
 9   City          48564 non-null  str
 10  Sport         48564 non-null  str
 11  Event         48564 non-null  str
 12  Medal         5695 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 4.8 MB

In [7]:
## Creating a data frame for only specific years or cities

yr_ct_sp_dfw = dfw[["Year", "City","Sport"]]
yr_ct_sp_dfw

       Year      City                 Sport
0      1924  Chamonix            Ice Hockey
1      1924  Chamonix       Nordic Combined
2      1924  Chamonix           Ski Jumping
3      1924  Chamonix  Cross Country Skiing
4      1924  Chamonix       Nordic Combined
...     ...       ...                   ...
48559  2014     Sochi         Alpine Skiing
48560  2014     Sochi         Alpine Skiing
48561  2014     Sochi         Alpine Skiing
48562  2014     Sochi           Ski Jumping
48563  2014     Sochi           Ski Jumping

[48564 rows x 3 columns]

In [8]:
yr_ct_sp_dfw.sort_values(by="Year", ascending = False)

       Year      City                 Sport
48563  2014     Sochi           Ski Jumping
45305  2014     Sochi              Biathlon
45298  2014     Sochi        Figure Skating
45299  2014     Sochi        Figure Skating
45300  2014     Sochi  Cross Country Skiing
...     ...       ...                   ...
311    1924  Chamonix  Cross Country Skiing
312    1924  Chamonix  Cross Country Skiing
313    1924  Chamonix  Cross Country Skiing
314    1924  Chamonix               Curling
0      1924  Chamonix            Ice Hockey

[48564 rows x 3 columns]

In [9]:
yr_ct_sp_dfw.sort_values(by="Sport")

       Year         City          Sport
38459  2006       Torino  Alpine Skiing
46398  2014        Sochi  Alpine Skiing
22547  1992  Albertville  Alpine Skiing
22546  1992  Albertville  Alpine Skiing
22545  1992  Albertville  Alpine Skiing
...     ...          ...            ...
19127  1988      Calgary  Speed Skating
43551  2010    Vancouver  Speed Skating
43550  2010    Vancouver  Speed Skating
43510  2010    Vancouver  Speed Skating
43512  2010    Vancouver  Speed Skating

[48564 rows x 3 columns]

In [10]:
yr_ct_sp_dfw.sort_values(by=["City", "Year"])

       Year         City                 Sport
20579  1992  Albertville         Speed Skating
20580  1992  Albertville         Speed Skating
20581  1992  Albertville  Cross Country Skiing
20582  1992  Albertville  Cross Country Skiing
20583  1992  Albertville  Cross Country Skiing
...     ...          ...                   ...
43668  2010    Vancouver         Alpine Skiing
43669  2010    Vancouver         Alpine Skiing
43670  2010    Vancouver              Biathlon
43671  2010    Vancouver         Alpine Skiing
43672  2010    Vancouver         Alpine Skiing

[48564 rows x 3 columns]

In [11]:
## We can create columns with known values
dfs["Season"] = "Summer"
dfs.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,Summer
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,Summer
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,Summer
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,Summer
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,Summer

In [12]:
dfw["Season"]="Winter"
dfw

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,Winter
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,Winter
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,Winter
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,Winter
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,Winter
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,Winter
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,Winter
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,Winter
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,Winter

In [13]:
## One equal sign is an assignment, two are a question

x = 12

x == 10

False

In [14]:
dfw.columns

Index(['ID', 'Athlete Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC',
       'Year', 'City', 'Sport', 'Event', 'Medal', 'Season'],
      dtype='str')

In [15]:
dfw.columns == dfs.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [16]:
#dfo = pd.concat([dfs,dfw]) - leads to wrong total index, below is fix
dfo = pd.concat([dfs,dfw], ignore_index = True)
dfo

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,Summer
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,Summer
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,Summer
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,Summer
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,Winter
271112,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,Winter
271113,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,Winter
271114,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,Winter
271115,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,Winter

In [17]:
dfo.query("City == 'Sochi' ")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
266225,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,Winter
266226,126,Forough Abbasi,F,20.0,164.0,58.0,Iran,IRI,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Slalom,NaN,Winter
266227,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Men's Singles,NaN,Winter
266228,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Mixed Team,Bronze,Winter
266229,463,Agnese boltia,F,17.0,166.0,60.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Super G,NaN,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,Winter
271112,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,Winter
271113,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,Winter
271114,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,Winter
271115,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,Winter

In [18]:
dfo.query("Sport == 'Ice Hockey'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
12651,5429,Karl Wilhelm Konrad Arwe (Andersson-),M,22.0,NaN,NaN,Sweden,SWE,1920,Antwerpen,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN,Summer
12775,10216,"Robert John ""Bobby"" Benson",M,25.0,167.0,61.0,Canada,CAN,1920,Antwerpen,Ice Hockey,Ice Hockey Men's Ice Hockey,Gold,Summer
12916,13265,"Raymond Leroy ""Ray"" Bonney",M,28.0,175.0,81.0,United States,USA,1920,Antwerpen,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,Summer
13075,16648,Hjalmar Eric Wilhelm Burman,M,22.0,NaN,NaN,Sweden,SWE,1920,Antwerpen,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN,Summer
13085,17100,"Jacob Walter ""Wally"" Byron",M,35.0,180.0,65.0,Canada,CAN,1920,Antwerpen,Ice Hockey,Ice Hockey Men's Ice Hockey,Gold,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270998,133605,Tom Zborsk,M,26.0,183.0,88.0,Slovakia,SVK,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN,Winter
271043,134391,Carl Henrik Zetterberg,M,33.0,183.0,86.0,Sweden,SWE,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,Winter
271080,134924,Marek idlick,M,37.0,180.0,85.0,Czech Republic,CZE,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN,Winter
271100,135255,Julia Zorn,F,24.0,170.0,73.0,Germany,GER,2014,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,NaN,Winter
271108,135365,Mats Andr Zuccarello-Aasen,M,26.0,171.0,74.0,Norway,NOR,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN,Winter

In [19]:
dfo.query ("`Athlete Name` == 'Forough Abbasi'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
266226,126,Forough Abbasi,F,20.0,164.0,58.0,Iran,IRI,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Slalom,NaN,Winter

In [20]:
dfo.query ("Year == 1900")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
380,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Summer
381,133,Franz Abb,M,NaN,NaN,NaN,Germany,GER,1900,Paris,Gymnastics,Gymnastics Men's Individual All-Around,NaN,Summer
382,150,Margaret Ives Abbott (-Dunne),F,23.0,NaN,NaN,United States,USA,1900,Paris,Golf,Golf Women's Individual,Gold,Summer
383,151,Mary Perkins Ives Abbott (Perkins-),F,42.0,NaN,NaN,United States,USA,1900,Paris,Golf,Golf Women's Individual,NaN,Summer
384,404,"Louis Grenville ""Lou"" Abell",M,15.0,NaN,NaN,Vesper Boat Club,USA,1900,Paris,Rowing,Rowing Men's Coxed Eights,Gold,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2311,131733,William Hayden Wright,M,NaN,NaN,NaN,A North American Team,USA,1900,Paris,Polo,Polo Men's Polo,Bronze,Summer
2312,133574,Henri Yvon,M,NaN,NaN,NaN,France,FRA,1900,Paris,Fencing,"Fencing Men's Foil, Masters, Individual",NaN,Summer
2313,133574,Henri Yvon,M,NaN,NaN,NaN,France,FRA,1900,Paris,Fencing,"Fencing Men's epee, Masters, Individual",NaN,Summer
2314,133807,Pyotr Antonovich Zakovorot,M,NaN,NaN,NaN,Russia,RUS,1900,Paris,Fencing,"Fencing Men's Sabre, Masters, Individual",NaN,Summer
2315,134198,"Walter John ""Jack"" Zealley",M,NaN,NaN,NaN,Upton Park FC,GBR,1900,Paris,Football,Football Men's Football,Gold,Summer

In [21]:
dfo.query("1940 <= Year <= 1960 ")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
36483,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,London,Gymnastics,Gymnastics Men's Individual All-Around,Bronze,Summer
36484,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,London,Gymnastics,Gymnastics Men's Team All-Around,Gold,Summer
36485,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,London,Gymnastics,Gymnastics Men's Floor Exercise,NaN,Summer
36486,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,London,Gymnastics,Gymnastics Men's Horse Vault,Gold,Summer
36487,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,London,Gymnastics,Gymnastics Men's Parallel Bars,NaN,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229422,134268,Kazimierz Zelek,M,22.0,169.0,64.0,Poland,POL,1960,Squaw Valley,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN,Winter
229423,134875,Nina Alekseyevna Zhuk (Bakusheva-),F,25.0,NaN,NaN,Soviet Union-1,URS,1960,Squaw Valley,Figure Skating,Figure Skating Mixed Pairs,NaN,Winter
229424,134876,Stanislav Alekseyevich Zhuk,M,25.0,NaN,NaN,Soviet Union-1,URS,1960,Squaw Valley,Figure Skating,Figure Skating Mixed Pairs,NaN,Winter
229425,135022,Josef Egon Norbert Zimmermann,M,27.0,NaN,NaN,Austria,AUT,1960,Squaw Valley,Alpine Skiing,Alpine Skiing Men's Downhill,NaN,Winter
229426,135376,Ross Barta Zucco,M,25.0,NaN,NaN,United States,USA,1960,Squaw Valley,Speed Skating,"Speed Skating Men's 10,000 metres",NaN,Winter

In [22]:
dfo.query("Year == 1936 & NOC == 'USA'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
30008,762,"Gordon Belgum ""Gordy"" Adam",M,21.0,NaN,NaN,United States,USA,1936,Berlin,Rowing,Rowing Men's Coxed Eights,Gold,Summer
30012,829,"Morgan Orlando Adams, Jr.",M,20.0,NaN,NaN,Mystery,USA,1936,Berlin,Sailing,Sailing Mixed 6 metres,NaN,Summer
30036,1339,William Alexander (Wilhelm Alexander-) Ahlemeyer,M,29.0,NaN,NaN,United States,USA,1936,Berlin,Handball,Handball Men's Handball,NaN,Summer
30054,2387,"David Donald ""Dave"" Albritton",M,23.0,191.0,79.0,United States,USA,1936,Berlin,Athletics,Athletics Men's High Jump,Silver,Summer
30063,2552,Hugh Vincenzo Alessandroni,M,28.0,NaN,NaN,United States,USA,1936,Berlin,Fencing,"Fencing Men's Foil, Individual",NaN,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224784,128832,"Alan Morgan ""Al"" Washbond",M,36.0,NaN,NaN,United States-1,USA,1936,Garmisch-Partenkirchen,Bobsleigh,Bobsleigh Men's Two,Gold,Winter
224785,128834,"Albert Lincoln ""Link"" Washburn",M,24.0,NaN,NaN,United States,USA,1936,Garmisch-Partenkirchen,Alpine Skiing,Alpine Skiing Men's Combined,NaN,Winter
224793,129326,Estelle D. Weigel (-Schmitt),F,21.0,NaN,NaN,United States,USA,1936,Garmisch-Partenkirchen,Figure Skating,Figure Skating Women's Singles,NaN,Winter
224794,129328,Louise E. Weigel (-Atwill),F,23.0,NaN,NaN,United States,USA,1936,Garmisch-Partenkirchen,Figure Skating,Figure Skating Women's Singles,NaN,Winter
224814,131578,"Elizabeth Davenport ""Betty"" Woolsey",F,27.0,NaN,NaN,United States,USA,1936,Garmisch-Partenkirchen,Alpine Skiing,Alpine Skiing Women's Combined,NaN,Winter

In [23]:
##But this went wrong
india_top_two = dfo.query("NOC == 'IND' & Medal == 'Gold' or Medal == 'Silver'")
india_top_two

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
5,4116,Ioannis Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Swimming,"Swimming Men's 1,200 metres Freestyle",Silver,Summer
15,12068,Arthur Charles Blake,M,24.0,NaN,NaN,United States,USA,1896,Athina,Athletics,"Athletics Men's 1,500 metres",Silver,Summer
28,17492,Eugne Henri Callot,M,20.0,NaN,NaN,France,FRA,1896,Athina,Fencing,"Fencing Men's Foil, Individual",Silver,Summer
29,18785,Demetrius Emmanuel Casdagli,M,23.0,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,Silver,Summer
30,18785,Demetrius Emmanuel Casdagli,M,23.0,NaN,NaN,Greece-1,GRE,1896,Athina,Tennis,Tennis Men's Doubles,Silver,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270948,132076,Xu Mengtao,F,23.0,165.0,59.0,China,CHN,2014,Sochi,Freestyle Skiing,Freestyle Skiing Women's Aerials,Silver,Winter
270968,132638,Dmitry Semyonovich Yaparov,M,28.0,186.0,86.0,Russia,RUS,2014,Sochi,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,Silver,Winter
271033,134154,Olga Alekseyevna Zaytseva (-Augustin),F,35.0,168.0,66.0,Russia,RUS,2014,Sochi,Biathlon,Biathlon Women's 4 x 6 kilometres Relay,Silver,Winter
271043,134391,Carl Henrik Zetterberg,M,33.0,183.0,86.0,Sweden,SWE,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,Winter
271093,135163,Luiza Zotkowska,F,27.0,160.0,52.0,Poland,POL,2014,Sochi,Speed Skating,Speed Skating Women's Team Pursuit (6 laps),Silver,Winter

In [24]:
india_dfo = dfo.query("NOC == 'IND'")

In [28]:
##HOMEWORK BEGINS HERE

## How many medals were handed out in winter games v summer games?

dfs["Medal"].value_counts()

Medal
Gold      11459
Bronze    11409
Silver    11220
Name: count, dtype: int64

In [29]:
dfw["Medal"].value_counts()

Medal
Gold      1913
Silver    1896
Bronze    1886
Name: count, dtype: int64

In [ ]:
##Summer Games had 34,088 Medals, Winter had 5695 Medals

In [40]:
dfo.query ("Medal == 'Gold'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
6,4189,Nikolaos Andriakopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Gymnastics,Gymnastics Men's Rope Climbing,Gold,Summer
19,12563,Conrad Helmut Fritz Bcker,M,25.0,NaN,NaN,Germany,GER,1896,Athina,Gymnastics,"Gymnastics Men's Parallel Bars, Teams",Gold,Summer
21,12563,Conrad Helmut Fritz Bcker,M,25.0,NaN,NaN,Germany,GER,1896,Athina,Gymnastics,"Gymnastics Men's Horizontal Bar, Teams",Gold,Summer
24,12929,John Mary Pius Boland,M,25.0,NaN,NaN,Great Britain,GBR,1896,Athina,Tennis,Tennis Men's Singles,Gold,Summer
25,12929,John Mary Pius Boland,M,25.0,NaN,NaN,Great Britain/Germany,GBR,1896,Athina,Tennis,Tennis Men's Doubles,Gold,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271007,133782,Ruslan Albertovich Zakharov,M,26.0,173.0,72.0,Russia,RUS,2014,Sochi,Short Track Speed Skating,"Short Track Speed Skating Men's 5,000 metres R...",Gold,Winter
271049,134463,Zhang Hong,F,25.0,174.0,65.0,China,CHN,2014,Sochi,Speed Skating,"Speed Skating Women's 1,000 metres",Gold,Winter
271072,134824,Zhou Yang,F,22.0,165.0,62.0,China,CHN,2014,Sochi,Short Track Speed Skating,"Short Track Speed Skating Women's 1,500 metres",Gold,Winter
271106,135343,Aleksandr Yuryevich Zubkov,M,39.0,189.0,102.0,Russia-1,RUS,2014,Sochi,Bobsleigh,Bobsleigh Men's Two,Gold,Winter
271107,135343,Aleksandr Yuryevich Zubkov,M,39.0,189.0,102.0,Russia-1,RUS,2014,Sochi,Bobsleigh,Bobsleigh Men's Four,Gold,Winter

In [47]:
dfo_topg = dfo.query("Medal == 'Gold'")["NOC"].value_counts().to_frame("Quantity").sort_values(by = "Quantity", ascending = False)
dfo_topg.head(10)

     Quantity
NOC
USA      2638
URS      1082
GER       745
GBR       678
ITA       575
FRA       501
SWE       479
CAN       463
HUN       432
GDR       397

In [50]:
round(dfo_topg.value_counts(normalize = True)*100,2)

Quantity
1           21.10
3            4.59
2            4.59
20           2.75
7            2.75
            ...
16           0.92
14           0.92
12           0.92
11           0.92
10           0.92
Name: proportion, Length: 67, dtype: float64

In [ ]:
##HOMEWORK ENDS HERE

## create more cells as necessary

In [30]:
## bring in our diamonds dataset
dfd = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/diamonds.csv")
dfd

       carat diamond cut color clarity  depth  table  price     x     y     z
0       0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...         ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72       Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72        Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75       Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [31]:
dfd["diamond cut"].nunique()

5

In [32]:
dfd["diamond cut"].value_counts(ascending = False)

diamond cut
Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: count, dtype: int64

In [33]:
dfd["diamond cut"].value_counts().to_frame("Quantity").sort_values(by = "Quantity", ascending = True)

             Quantity
diamond cut
Fair             1610
Good             4906
Very Good       12082
Premium         13791
Ideal           21551

In [34]:
## Normailze gives you the percentages
dfd["diamond cut"].value_counts(normalize = True)

diamond cut
Ideal        0.399537
Premium      0.255673
Very Good    0.223990
Good         0.090953
Fair         0.029848
Name: proportion, dtype: float64

In [35]:
round(dfd["diamond cut"].value_counts(normalize = True),2)

diamond cut
Ideal        0.40
Premium      0.26
Very Good    0.22
Good         0.09
Fair         0.03
Name: proportion, dtype: float64

In [36]:
round(dfd["diamond cut"].value_counts(normalize = True) *100 ,1)

diamond cut
Ideal        40.0
Premium      25.6
Very Good    22.4
Good          9.1
Fair          3.0
Name: proportion, dtype: float64